/***Images for the map*/
const map = {
    beacon: "img/beacon.png",
    crate_death: "img/create_death.png",
    crate_loot: "img/crate_loot.png",
    drone: "img/drone.png",
    drone_station: "img/drone_station.png",
    drop_pod: "img/drop_pod.png",
    explorer: "img/explorer.png",
    factory_cart: "img/factory_cart.png",
    hub: "img/hub.png",
    map: "img/map.png",
    player: "img/player.png",
    player_dead: "img/player_dead.png",
    player_offline: "img/player_offline.png",
    portal: "img/portal.png",
    portal_satellite: "img/portal_satellite.png",
    power: "img/power.png",
    power_slug: "img/power_slug.png",
    power_slug_mk1: "img/power_slug_mk1.png",
    power_slug_mk2: "img/power_slug_mk2.png",
    power_slug_mk3: "img/power_slug_mk3.png",
    question_mark: "img/question_mark.png",
    radar_tower: "img/radar_tower.png",
    radiation: "img/radiation.png",
    recycle: "img/recycle.png",
    space_elevator: "img/space_elevator.png",
    tape: "img/tape.png",
    tractor: "img/tractor.png",
    train: "img/train.png",
    train_station: "img/train_station.png",
    truck: "img/truck.png",
    truck_station: "img/truck_station.png",
    vehicle_receive: "img/vehicle_receive.png",
    vehicle_sending: "img/vehicle_sending.png",
};

const resources = {
    bauxite: "img/resources/Desc_OreBauxite_C.png",
    caterium: "img/resources/Desc_OreGold_C.png",
    coal: "img/resources/Desc_Coal_C.png",
    copper: "img/resources/Desc_OreCopper_C.png",
    geyser: "img/resources/Desc_Geyser_C.png",
    iron: "img/resources/Desc_OreIron_C.png",
    limestone: "img/resources/Desc_Stone_C.png",
    nitrogen_gas: "img/resources/Desc_NitrogenGas_C.png",
    path: "img/resources/",
    raw_quartz: "img/resources/Desc_RawQuartz_C.png",
    sam: "img/resources/Desc_SAM_C.png",
    sulfur: "img/resources/Desc_Sulfur_C.png",
    uranium: "img/resources/Desc_OreUranium_C.png",
    water: "img/resources/Desc_Water_C.png",
}

export const images = {map: map, resources: resources};
